"""empty message

Revision ID: 23759a13c97d
Revises: 
Create Date: 2018-11-05 22:56:14.340386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23759a13c97d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_admin_auth_addtime'), 'admin_auth', ['addtime'], unique=False)
    op.create_table('admin_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('auths', sa.String(length=600), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_admin_role_addtime'), 'admin_role', ['addtime'], unique=False)
    op.create_table('album_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('addtime', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_album_tag_addtime'), 'album_tag', ['addtime'], unique=False)
    op.create_table('article_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('addtime', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_article_tag_addtime'), 'article_tag', ['addtime'], unique=False)
    op.create_table('movie_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('addtime', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_movie_tag_addtime'), 'movie_tag', ['addtime'], unique=False)
    op.create_table('music_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('addtime', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_music_category_addtime'), 'music_category', ['addtime'], unique=False)
    op.create_table('music_emotion_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('addtime', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_music_emotion_tag_addtime'), 'music_emotion_tag', ['addtime'], unique=False)
    op.create_table('music_lang_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('addtime', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_music_lang_tag_addtime'), 'music_lang_tag', ['addtime'], unique=False)
    op.create_table('music_scene_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('addtime', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_music_scene_tag_addtime'), 'music_scene_tag', ['addtime'], unique=False)
    op.create_table('music_style_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('addtime', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_music_style_tag_addtime'), 'music_style_tag', ['addtime'], unique=False)
    op.create_table('music_theme_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('addtime', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_music_theme_tag_addtime'), 'music_theme_tag', ['addtime'], unique=False)
    op.create_table('timeline_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=150), nullable=False),
    sa.Column('reciever', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('content', sa.String(length=512), nullable=False),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_item_addtime'), 'timeline_item', ['addtime'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('pwd', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=120), nullable=False),
    sa.Column('face', sa.String(length=255), nullable=False),
    sa.Column('jianjie', sa.TEXT(), nullable=True),
    sa.Column('uuid', sa.String(length=255), nullable=False),
    sa.Column('addtime', sa.DATETIME(), nullable=True),
    sa.Column('fanscount', sa.Integer(), nullable=True),
    sa.Column('ouxiangcount', sa.Integer(), nullable=True),
    sa.Column('friendcount', sa.Integer(), nullable=True),
    sa.Column('creator_score', sa.Integer(), nullable=True),
    sa.Column('albums_score', sa.Integer(), nullable=True),
    sa.Column('articles_score', sa.Integer(), nullable=True),
    sa.Column('comments_score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('face'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('pwd'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_user_addtime'), 'user', ['addtime'], unique=False)
    op.create_table('user_friend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_id', sa.Integer(), nullable=True),
    sa.Column('to_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('addtime', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_friend_addtime'), 'user_friend', ['addtime'], unique=False)
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('pwd', sa.String(length=255), nullable=False),
    sa.Column('is_super', sa.SmallInteger(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.String(length=255), nullable=False),
    sa.Column('addtime', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['admin_role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('pwd'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_admin_addtime'), 'admin', ['addtime'], unique=False)
    op.create_table('album',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('desc', sa.TEXT(), nullable=True),
    sa.Column('cover', sa.String(length=255), nullable=True),
    sa.Column('photonum', sa.Integer(), nullable=True),
    sa.Column('privacy', sa.String(length=20), nullable=True),
    sa.Column('recommed', sa.Integer(), nullable=True),
    sa.Column('clicknum', sa.Integer(), nullable=True),
    sa.Column('favornum', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.String(length=255), nullable=False),
    sa.Column('addtime', sa.DATETIME(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['album_tag.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_album_addtime'), 'album', ['addtime'], unique=False)
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('abstract', sa.TEXT(), nullable=True),
    sa.Column('cover', sa.String(length=255), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('privacy', sa.String(length=20), nullable=True),
    sa.Column('recommed', sa.Integer(), nullable=True),
    sa.Column('clicknum', sa.Integer(), nullable=True),
    sa.Column('favornum', sa.Integer(), nullable=True),
    sa.Column('commtnum', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.String(length=255), nullable=False),
    sa.Column('addtime', sa.DATETIME(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['article_tag.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_article_addtime'), 'article', ['addtime'], unique=False)
    op.create_table('music_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('addtime', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['music_category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_music_tag_addtime'), 'music_tag', ['addtime'], unique=False)
    op.create_table('user_follow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('addtime', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_follow_addtime'), 'user_follow', ['addtime'], unique=False)
    op.create_table('admin_loginlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=100), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_loginlog_addtime'), 'admin_loginlog', ['addtime'], unique=False)
    op.create_table('admin_operatelog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=100), nullable=True),
    sa.Column('operations', sa.String(length=600), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_operatelog_addtime'), 'admin_operatelog', ['addtime'], unique=False)
    op.create_table('album_favor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.Column('addtime', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_album_favor_addtime'), 'album_favor', ['addtime'], unique=False)
    op.create_table('article_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.TEXT(), nullable=True),
    sa.Column('addtime', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_comment_addtime'), 'article_comment', ['addtime'], unique=False)
    op.create_table('article_favor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('addtime', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_favor_addtime'), 'article_favor', ['addtime'], unique=False)
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('cover', sa.String(length=255), nullable=True),
    sa.Column('videofile', sa.String(length=255), nullable=True),
    sa.Column('privacy', sa.String(length=20), nullable=True),
    sa.Column('area', sa.String(length=20), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('starlevel', sa.SmallInteger(), nullable=True),
    sa.Column('recommed', sa.Integer(), nullable=True),
    sa.Column('clicknum', sa.Integer(), nullable=True),
    sa.Column('favornum', sa.Integer(), nullable=True),
    sa.Column('commtnum', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.String(length=255), nullable=False),
    sa.Column('addtime', sa.DATETIME(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['movie_tag.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_movie_addtime'), 'movie', ['addtime'], unique=False)
    op.create_table('music',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('singer', sa.String(length=255), nullable=False),
    sa.Column('coverfile', sa.String(length=255), nullable=True),
    sa.Column('audiofile', sa.String(length=255), nullable=True),
    sa.Column('lrcfile', sa.String(length=255), nullable=True),
    sa.Column('privacy', sa.String(length=20), nullable=True),
    sa.Column('recommed', sa.Integer(), nullable=True),
    sa.Column('clicknum', sa.Integer(), nullable=True),
    sa.Column('favornum', sa.Integer(), nullable=True),
    sa.Column('commtnum', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.String(length=255), nullable=False),
    sa.Column('addtime', sa.DATETIME(), nullable=True),
    sa.Column('lang_id', sa.Integer(), nullable=True),
    sa.Column('style_id', sa.Integer(), nullable=True),
    sa.Column('theme_id', sa.Integer(), nullable=True),
    sa.Column('emotion_id', sa.Integer(), nullable=True),
    sa.Column('scene_id', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.ForeignKeyConstraint(['emotion_id'], ['music_emotion_tag.id'], ),
    sa.ForeignKeyConstraint(['lang_id'], ['music_lang_tag.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['music_scene_tag.id'], ),
    sa.ForeignKeyConstraint(['style_id'], ['music_style_tag.id'], ),
    sa.ForeignKeyConstraint(['theme_id'], ['music_theme_tag.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_music_addtime'), 'music', ['addtime'], unique=False)
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origname', sa.String(length=255), nullable=False),
    sa.Column('showname', sa.String(length=255), nullable=False),
    sa.Column('thumbname', sa.String(length=255), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.Column('addtime', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('origname'),
    sa.UniqueConstraint('showname'),
    sa.UniqueConstraint('thumbname')
    )
    op.create_index(op.f('ix_photo_addtime'), 'photo', ['addtime'], unique=False)
    op.create_table('user_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('content', sa.String(length=600), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_message_addtime'), 'user_message', ['addtime'], unique=False)
    op.create_table('movie_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.TEXT(), nullable=True),
    sa.Column('addtime', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_comment_addtime'), 'movie_comment', ['addtime'], unique=False)
    op.create_table('movie_favor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('addtime', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_favor_addtime'), 'movie_favor', ['addtime'], unique=False)
    op.create_table('music_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('music_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.TEXT(), nullable=True),
    sa.Column('addtime', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['music_id'], ['music.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_music_comment_addtime'), 'music_comment', ['addtime'], unique=False)
    op.create_table('music_favor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('music_id', sa.Integer(), nullable=True),
    sa.Column('addtime', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['music_id'], ['music.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_music_favor_addtime'), 'music_favor', ['addtime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_music_favor_addtime'), table_name='music_favor')
    op.drop_table('music_favor')
    op.drop_index(op.f('ix_music_comment_addtime'), table_name='music_comment')
    op.drop_table('music_comment')
    op.drop_index(op.f('ix_movie_favor_addtime'), table_name='movie_favor')
    op.drop_table('movie_favor')
    op.drop_index(op.f('ix_movie_comment_addtime'), table_name='movie_comment')
    op.drop_table('movie_comment')
    op.drop_index(op.f('ix_user_message_addtime'), table_name='user_message')
    op.drop_table('user_message')
    op.drop_index(op.f('ix_photo_addtime'), table_name='photo')
    op.drop_table('photo')
    op.drop_index(op.f('ix_music_addtime'), table_name='music')
    op.drop_table('music')
    op.drop_index(op.f('ix_movie_addtime'), table_name='movie')
    op.drop_table('movie')
    op.drop_index(op.f('ix_article_favor_addtime'), table_name='article_favor')
    op.drop_table('article_favor')
    op.drop_index(op.f('ix_article_comment_addtime'), table_name='article_comment')
    op.drop_table('article_comment')
    op.drop_index(op.f('ix_album_favor_addtime'), table_name='album_favor')
    op.drop_table('album_favor')
    op.drop_index(op.f('ix_admin_operatelog_addtime'), table_name='admin_operatelog')
    op.drop_table('admin_operatelog')
    op.drop_index(op.f('ix_admin_loginlog_addtime'), table_name='admin_loginlog')
    op.drop_table('admin_loginlog')
    op.drop_index(op.f('ix_user_follow_addtime'), table_name='user_follow')
    op.drop_table('user_follow')
    op.drop_index(op.f('ix_music_tag_addtime'), table_name='music_tag')
    op.drop_table('music_tag')
    op.drop_index(op.f('ix_article_addtime'), table_name='article')
    op.drop_table('article')
    op.drop_index(op.f('ix_album_addtime'), table_name='album')
    op.drop_table('album')
    op.drop_index(op.f('ix_admin_addtime'), table_name='admin')
    op.drop_table('admin')
    op.drop_index(op.f('ix_user_friend_addtime'), table_name='user_friend')
    op.drop_table('user_friend')
    op.drop_index(op.f('ix_user_addtime'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_timeline_item_addtime'), table_name='timeline_item')
    op.drop_table('timeline_item')
    op.drop_index(op.f('ix_music_theme_tag_addtime'), table_name='music_theme_tag')
    op.drop_table('music_theme_tag')
    op.drop_index(op.f('ix_music_style_tag_addtime'), table_name='music_style_tag')
    op.drop_table('music_style_tag')
    op.drop_index(op.f('ix_music_scene_tag_addtime'), table_name='music_scene_tag')
    op.drop_table('music_scene_tag')
    op.drop_index(op.f('ix_music_lang_tag_addtime'), table_name='music_lang_tag')
    op.drop_table('music_lang_tag')
    op.drop_index(op.f('ix_music_emotion_tag_addtime'), table_name='music_emotion_tag')
    op.drop_table('music_emotion_tag')
    op.drop_index(op.f('ix_music_category_addtime'), table_name='music_category')
    op.drop_table('music_category')
    op.drop_index(op.f('ix_movie_tag_addtime'), table_name='movie_tag')
    op.drop_table('movie_tag')
    op.drop_index(op.f('ix_article_tag_addtime'), table_name='article_tag')
    op.drop_table('article_tag')
    op.drop_index(op.f('ix_album_tag_addtime'), table_name='album_tag')
    op.drop_table('album_tag')
    op.drop_index(op.f('ix_admin_role_addtime'), table_name='admin_role')
    op.drop_table('admin_role')
    op.drop_index(op.f('ix_admin_auth_addtime'), table_name='admin_auth')
    op.drop_table('admin_auth')
    # ### end Alembic commands ###
